# Generated by Django 5.2.15 on 2026-06-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WalkingRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("distance_km", models.DecimalField(decimal_places=1, max_digits=4)),
                ("duration_hours", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                ("neighbourhood", models.CharField(blank=True, max_length=100)),
                ("cover_image", models.ImageField(blank=True, upload_to="routes/")),
                (
                    "preview_image",
                    models.ImageField(blank=True, upload_to="routes/previews/"),
                ),
                (
                    "etsy_listing_url",
                    models.URLField(blank=True, help_text="Link to purchase on Etsy"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Walking Route",
                "verbose_name_plural": "Walking Routes",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
