import type { ArtPiece, Collection, GuidedTour, TourDate, WalkingRoute } from "@/types";

export const SITE_SETTINGS = {
  tagline: "Hand-drawn maps & guided walks through Porto's soul.",
  hero_subtitle:
    "Original ink illustrations, self-guided walking routes and intimate guided tours — all created by one artist who lives, breathes and draws this city.",
  etsy_shop_url: "https://www.etsy.com/shop/SharonJemimaArt",
  instagram_url: "https://www.instagram.com/theportomap",
  facebook_url: "",
};

export const MOCK_ROUTES: WalkingRoute[] = [
  {
    id: "1",
    title: "Ribeira, Line by Line",
    slug: "ribeira-line-by-line",
    subtitle: "The riverfront district, drawn house by house",
    description:
      "Sharon's most-loved route follows the Douro from Cais da Ribeira up through the tangle of stairs behind it. The printed script folds out into a hand-drawn map of every façade worth stopping for, with notes on which café has the best pastel de nata and which alley nobody photographs.",
    distance_km: 3.2,
    duration_hours: 2,
    difficulty: "easy",
    neighbourhood: "Ribeira",
    cover_image_url: "",
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    price: 8,
    featured: true,
    order: 1,
  },
  {
    id: "2",
    title: "Clérigos & the Booksellers",
    slug: "clerigos-and-the-booksellers",
    subtitle: "Towers, tiles and the smell of old paper",
    description:
      "A short walk through the university quarter — the Clérigos Tower, Livraria Lello's carved staircase, and the second-hand bookshops tucked between them. Includes Sharon's ink sketch of the tower drawn from three different angles, because one never did it justice.",
    distance_km: 2.1,
    duration_hours: 1.5,
    difficulty: "easy",
    neighbourhood: "Baixa",
    cover_image_url: "",
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    price: 7,
    featured: true,
    order: 2,
  },
  {
    id: "3",
    title: "Vila Nova de Gaia, Across the Bridge",
    slug: "gaia-across-the-bridge",
    subtitle: "Port wine cellars and the view everyone comes for",
    description:
      "Cross the Dom Luís I on the upper deck, then wind down into the wine lodges of Gaia. This route script maps out which cellars welcome walk-ins, where to watch the sunset with the whole of Porto lit up across the water, and a detour to a bakery no guidebook mentions.",
    distance_km: 4.5,
    duration_hours: 2.5,
    difficulty: "moderate",
    neighbourhood: "Vila Nova de Gaia",
    cover_image_url: "",
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    price: 9,
    featured: true,
    order: 3,
  },
  {
    id: "4",
    title: "Foz, Where the River Meets the Sea",
    slug: "foz-river-meets-sea",
    subtitle: "A coastal walk for slow mornings",
    description:
      "Porto's quieter side — the lighthouse, the Atlantic promenade, and the fort at the river mouth. Longer and flatter than the others, this route script is built for a lazy half-day with plenty of stops for coffee and sea air.",
    distance_km: 5.8,
    duration_hours: 3,
    difficulty: "moderate",
    neighbourhood: "Foz do Douro",
    cover_image_url: "",
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    price: 9,
    featured: false,
    order: 4,
  },
  {
    id: "5",
    title: "Bonfim's Backstreets",
    slug: "bonfim-backstreets",
    subtitle: "The neighbourhood locals actually live in",
    description:
      "No landmarks, no queues — just tiled façades, corner cafés and the cemetery gardens of a residential neighbourhood most visitors never see. Sharon drew this one for people who've already done the postcard routes.",
    distance_km: 3.6,
    duration_hours: 2,
    difficulty: "easy",
    neighbourhood: "Bonfim",
    cover_image_url: "",
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    price: 7,
    featured: false,
    order: 5,
  },
  {
    id: "6",
    title: "The Miradouros Trail",
    slug: "miradouros-trail",
    subtitle: "Six viewpoints, one long golden hour",
    description:
      "A hillier route stitched together from Sharon's own habit of chasing sunset light across the city. Six viewpoints, timed for late afternoon, with a fold-out panorama sketch at the back of the script.",
    distance_km: 6.4,
    duration_hours: 3.5,
    difficulty: "challenging",
    neighbourhood: "Vitória",
    cover_image_url: "",
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    price: 10,
    featured: false,
    order: 6,
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: "c1",
    name: "Porto Landmarks",
    slug: "porto-landmarks",
    description: "The buildings everyone recognises, drawn the way Sharon actually sees them.",
    order: 1,
  },
  {
    id: "c2",
    name: "Ribeira Scenes",
    slug: "ribeira-scenes",
    description: "Life along the riverfront — boats, laundry lines, café terraces.",
    order: 2,
  },
];

export const MOCK_ART: ArtPiece[] = [
  {
    id: "a1",
    collection_slug: "porto-landmarks",
    title: "Clérigos at Dusk",
    slug: "clerigos-at-dusk",
    description: "Ink study of the tower as the last light hits the belfry.",
    medium: "ink",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: true,
    order: 1,
  },
  {
    id: "a2",
    collection_slug: "porto-landmarks",
    title: "São Bento, Tile by Tile",
    slug: "sao-bento-tile-by-tile",
    description: "A close study of the station's azulejo panels, drawn tile by tile over three sittings.",
    medium: "ink",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: true,
    order: 2,
  },
  {
    id: "a3",
    collection_slug: "porto-landmarks",
    title: "Dom Luís I, From Below",
    slug: "dom-luis-from-below",
    description: "The iron bridge seen from the Ribeira quay, looking straight up through its arches.",
    medium: "watercolour",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: false,
    order: 3,
  },
  {
    id: "a4",
    collection_slug: "ribeira-scenes",
    title: "Laundry Over the Douro",
    slug: "laundry-over-the-douro",
    description: "Washing lines strung between two Ribeira windows, river beyond.",
    medium: "ink",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: true,
    order: 4,
  },
  {
    id: "a5",
    collection_slug: "ribeira-scenes",
    title: "Rabelo Boats at Rest",
    slug: "rabelo-boats-at-rest",
    description: "The old Port wine boats moored along Cais da Ribeira on a quiet Tuesday.",
    medium: "mixed",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: false,
    order: 5,
  },
  {
    id: "a6",
    collection_slug: "ribeira-scenes",
    title: "Café Terrace, Praça da Ribeira",
    slug: "cafe-terrace-praca-da-ribeira",
    description: "Sketched from a corner table over a slow bica.",
    medium: "watercolour",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: false,
    order: 6,
  },
  {
    id: "a7",
    collection_slug: "porto-landmarks",
    title: "Livraria Lello Staircase",
    slug: "livraria-lello-staircase",
    description: "The famous red staircase, drawn from the mezzanine looking down.",
    medium: "ink",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: false,
    order: 7,
  },
  {
    id: "a8",
    collection_slug: "ribeira-scenes",
    title: "Fishmonger's Morning",
    slug: "fishmongers-morning",
    description: "The early market stalls behind Praça da Ribeira, before the tourists arrive.",
    medium: "ink",
    image_url: "",
    is_available: true,
    etsy_listing_url: "https://www.etsy.com/shop/SharonJemimaArt",
    featured: false,
    order: 8,
  },
];

export const MOCK_TOURS: GuidedTour[] = [
  {
    id: "t1",
    name: "Ribeira & the River, With Sharon",
    slug: "ribeira-and-the-river",
    tagline: "The route that started it all — now walked, not just drawn.",
    description:
      "Sharon's original walking route, but in person. Two hours along the Douro through Ribeira's stairs and hidden courtyards, stopping wherever the light or the conversation demands. This is the tour she recommends first.",
    duration_hours: 2,
    max_participants: 8,
    price_per_person: 35,
    meeting_point: "Praça da Ribeira Fountain",
    cover_image_url: "",
    highlights: [
      "The courtyards and stairways behind Cais da Ribeira",
      "Sharon's own sketching spots along the river",
      "A stop at the café she's painted more than any other building",
      "Small group — max 8 people",
    ],
    featured: true,
    order: 1,
  },
  {
    id: "t2",
    name: "Sketchbook Walk: Clérigos & Bolhão",
    slug: "sketchbook-walk-clerigos-bolhao",
    tagline: "Bring your own notebook — or just watch Sharon fill hers.",
    description:
      "Part walking tour, part live drawing demonstration. Sharon walks the group from the Clérigos Tower to the restored Bolhão Market, pausing to sketch and talk through why she chooses the angles she does. Sketchbooks welcome, but not required.",
    duration_hours: 2.5,
    max_participants: 6,
    price_per_person: 42,
    meeting_point: "Clérigos Tower, Main Entrance",
    cover_image_url: "",
    highlights: [
      "Live sketching demonstrations along the route",
      "Bolhão Market's restored iron-and-glass interior",
      "Tips on drawing architecture on location",
      "Small group — max 6 people",
    ],
    featured: true,
    order: 2,
  },
  {
    id: "t3",
    name: "Gaia Cellars & Sunset",
    slug: "gaia-cellars-and-sunset",
    tagline: "Port wine, hillside views, and the golden hour over Porto.",
    description:
      "An evening tour timed to end exactly when the light turns gold over the Douro. Starts in the wine lodges of Gaia, finishes on the terraces above Jardim do Morro with the whole city glowing across the water.",
    duration_hours: 2,
    max_participants: 8,
    price_per_person: 38,
    meeting_point: "Jardim do Morro (Gaia side of Dom Luís I Bridge)",
    cover_image_url: "",
    highlights: [
      "A short tasting at one of Gaia's historic wine lodges",
      "The terrace viewpoints above Jardim do Morro",
      "Timed to end during golden hour",
      "Small group — max 8 people",
    ],
    featured: false,
    order: 3,
  },
];

export const MOCK_TOUR_DATES: TourDate[] = [
  {
    id: "d1",
    tour_slug: "ribeira-and-the-river",
    date: "2026-08-14",
    time: "10:00",
    spots_remaining: 4,
    status: "available",
  },
  {
    id: "d2",
    tour_slug: "sketchbook-walk-clerigos-bolhao",
    date: "2026-08-16",
    time: "16:00",
    spots_remaining: 2,
    status: "available",
  },
  {
    id: "d3",
    tour_slug: "gaia-cellars-and-sunset",
    date: "2026-08-21",
    time: "19:00",
    spots_remaining: 6,
    status: "available",
  },
  {
    id: "d4",
    tour_slug: "ribeira-and-the-river",
    date: "2026-08-23",
    time: "10:00",
    spots_remaining: 0,
    status: "full",
  },
];
