# Generated by Django 5.2.15 on 2026-06-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArtPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("ink", "Ink on Paper"),
                            ("watercolour", "Watercolour"),
                            ("mixed", "Mixed Media"),
                        ],
                        default="ink",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="art/")),
                ("is_available", models.BooleanField(default=True)),
                ("etsy_listing_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces",
                        to="art.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Art Piece",
                "verbose_name_plural": "Art Pieces",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
