# Generated by Django 5.2.15 on 2026-06-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuidedTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=2.0, max_digits=3),
                ),
                ("max_participants", models.PositiveSmallIntegerField(default=8)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("meeting_point", models.CharField(max_length=300)),
                ("cover_image", models.ImageField(blank=True, upload_to="tours/")),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Guided Tour",
                "verbose_name_plural": "Guided Tours",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TourDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("spots_remaining", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("full", "Fully Booked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="tours.guidedtour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Date",
                "verbose_name_plural": "Tour Dates",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="TourBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("participants", models.PositiveSmallIntegerField(default=1)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tour_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="tours.tourdate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Booking",
                "verbose_name_plural": "Tour Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
