# Generated by Django 5.2.15 on 2026-06-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Hand-drawn maps & guided walks through Porto's soul.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Original ink illustrations, self-guided walking routes and intimate guided tours — all created by one artist who lives, breathes and draws this city."
                    ),
                ),
                (
                    "etsy_shop_url",
                    models.URLField(
                        blank=True, default="https://www.etsy.com/shop/SharonJemimaArt"
                    ),
                ),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
